fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        args: [src, --diff, --check]

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        args: [--errors-only,  --disable=E1101, --disable=E0401, --disable=E0611, --ignore-paths="^src/migrations/.*$"]