version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: "false"
      discovery.type: "single-node"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - elk_net

  kibana:
    image: kibana:8.5.3
    environment:
      SERVER_NAME: "kibana.example.org"
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200","https://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - elk_net
    depends_on:
      - elasticsearch

networks:
  elk_net:
