"""empty message

Revision ID: 2204eeb6a106
Revises: ca93ba7eb98f
Create Date: 2022-10-24 21:58:16.812642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2204eeb6a106"
down_revision = "ca93ba7eb98f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
