jwt_secret: a_very_important_secret
default_redirection_url: https://public.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: public.example.com
      policy: bypass
    - domain: traefik.example.com
      policy: one_factor
    - domain: secure.example.com
      policy: two_factor

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: this_is_a_secret_abc123abc123abc
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAyMR8hXotntiBPO32q8lQr6lWO7LOOa/eYIEMLXeoCMahp6zy
      oHXZpKkQojz4QYuCZqrnSoZfUDVNFFvJ87iMzKSH+xx/78iaWoKVUjhs3VWQM4z6
      qyn4sIciPL9EavjB33A6cKxx+mJ25k3NnaAEp7f1xbVwMN0TkrPaHVri2BMOA6DP
      d55nWQwmlo3jJK3Yi6t8vXEPWbbR88d/SlRiMgS/cA9Sv9M8nkIj3VLy35vOZSNI
      j6rqZ0/a7rUg825rzH6Y8jOzjOW5pCCfjuUs+7zgtZmdPrs2K8e2XF9K7tdQuXWQ
      PQQg1xiqIUN1FUYcaTcK6Ff+6R5ai6bIO3omUQIDAQABAoIBAQCJvy4EUoicdMVv
      LYHR6YT/kPqGaS7PK5gytDfLtk5G/ymIpsOtTk5uiETOW3ClX/evQ1D/s+QPXxKs
      hjGwk42fFr/pjWtF9Gfa879Js0cWMQ+IHxEZgOmNDJpz/XMOxfAWwqSGC/sDpK0Z
      ZIZPwKuQ+0mYRd1c2UIFpHphK6t6PZhhWMAx0w5yHjPl3DijTeoV2mm7XKweyaNi
      YsEQpFHDF07+/ZuA10XdgfMM2DMI5Sdk60zViUCuk+puV31OEewKjrQHSEMDq1f5
      5l27XoH/x3Df0ZlOp4UsaTO38eTLf0ERgk1CZVa31Nn0rpIjHueDoeb6Fy6WhHfA
      0Aor1yGFAoGBANAPdlU796ece2u0GXiJnSdoyuMB3s9kfUgOsbZwss+ofNXiINAQ
      xsWL4w/9/iD4nhtcOBCltHpcuL/Yt9YUPR9cUnXtFZB+RQUEUxXMIVpIjSVAQ5Yx
      civUIp1tk31mhSDVdIurPiBDzEK77UAzuPXw+KOltqEg8y03xqORT7QDAoGBAPcG
      2cQT56a4GpIhp9R22kGDrwUQfByJg6c88wNOjXeN5D78k+7E06/17EY/fufWjxxX
      /UX4vfP5O87G4w3RuIxjcwVdE+vjqINby1TKq+0Uxemc0nuUzegEiwnQ8sCYVghU
      QcrC3oRbjUwq2Kci5LFa6M/wCVbq3/MhAzymvg4bAoGAV/5CGJgtDEkk9Y8MuqrQ
      uSsbq1hOKD4isgfs5vDQ3vwuF7L0F6sQtdmMpWXRRZaAH6gn2fqK0rlGNXTtgu+6
      TfoYseEcHqkYfZ+vl+dmL63BbAC61NmCpMCqBxShrQZfxVwhVzSMKM8joxGhrGZz
      kihgr61VCN5LmlMdgm3hXIsCgYEAxmc1LlwCWZBSnv3zCx1ujOIUB1BHLrBwEjlM
      wWItE1HeeYxp0IM7tn8hhwZmihR1GwG8xZ9UCYkrNRfes3G29OLHNg6c+n/+D4sB
      k5e4YJGnp8sx7toESw6jEX5GCtQPfV8W/KBpEgtqQDvFiO/omF340VHsXmgE+QSR
      0fvmd/MCgYEAgKCQv7gsc2pgYJ6FjYdGnB1PHkYKzw3L+6LvsV9BcGgXiGV+in0U
      dOWsbFL90ZhzsDZmjpjQVnSAzMlmIgnkTmiPtnGqz7eDowbNz95P+zJlRUSplHIv
      kieK3/GMGlvkyDUfl4RkIMt/WnpZP3/PHSe/o6GN7iQ7C0CNGBsnzLg=
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins: "*"
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: app
        description: My Application
        secret: app_secret
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: [ ]
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://ya.ru
        grant_types:
          - refresh_token
          - authorization_code
          - password
        response_types:
          - code
        userinfo_signing_algorithm: none
