name: Code quality checks

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: pip install --upgrade pip
    - run: pip install black==22.8.0 pylint==2.15.3 isort==5.10.1
    - run: black --diff --check $(git ls-files '*.py') 
    - run: pylint --errors-only --disable=E0401,E0611,E1101 --ignore-paths="^src/migrations/.*$" $(git ls-files '*.py')
    - run: isort --profile=black --check-only --diff $(git ls-files '*.py')